x-description: "production environment, with images from container registry"
version: "2.4"
services:
  powerberry-app:
    extends:
      file: docker-compose.base.yml
      service: powerberry-app
    image: ghcr.io/steckdoose4711/powerberry-app:latest

  powerberry-dsp:
    extends:
      file: docker-compose.base.yml
      service: powerberry-dsp
    image: ghcr.io/steckdoose4711/powerberry-dsp:latest
    volumes:
      - /sys:/app/sys

  powerberry-redis:
    extends:
      file: docker-compose.base.yml
      service: powerberry-redis
