version: "3"
services:
  powerberry-app:
    container_name: powerberry-app
    build: powerberry-app
    restart: 'always'
    volumes:
      - ./config:/config:ro
    environment:
      CONFIG_PATH: /config/config.json
      REDIS_HOST: powerberry-redis
      REDIS_PORT: 6379
  powerberry-dsp:
    container_name: powerberry-dsp
    build: powerberry-dsp
    restart: 'no'
    volumes:
      - ./config:/config:ro
  powerberry-redis:
    container_name: powerberry-redis
    image: redis:6-alpine
    restart: 'always'
    # use redis as a pure in-memory store
    command: |
      --save "" --appendonly no
