influxdb:
  image: influxdb:1.8.10
  restart: always
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/influxdb/data
    - /home/pi/docker/influxdb/data:/var/lib/influxdb

grafana:
  image: grafana/grafana:8.4.6
  restart: always
  container_name: grafana
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  user: "0"
  links:
    - influxdb
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
    - /home/pi/docker/grafana:/var/lib/grafana
