version: "2.4"
services:
  powerberry-app:
    extends:
      file: docker-compose.prod.yml
      service: powerberry-app
    volumes:
      - ./powerberry-app:/app
      - ./config:/config

  # for dev, we use the container with sdk tools and bind mounts
  powerberry-dsp:
    extends:
      file: docker-compose.prod.yml
      service: powerberry-dsp
    build:
      context: ./powerberry-dsp
      target: dev
    volumes:
      - ./powerberry-dsp:/app
      - ./config:/config
    environment:
      EMULATE_HARDWARE: emu_hw_true    

  powerberry-redis:
    extends:
      file: docker-compose.prod.yml
      service: powerberry-redis

  powerberry-influx:
    container_name: powerberry-influxdb-dev
    image: influxdb:latest
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb

  powerberry-grafana:
    container_name: powerberry-grafana-dev
    image: grafana/grafana:latest
    restart: always    
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana