x-description: "local development environment, with built images from sources"
version: "2.4"
services:
  powerberry-app:
    extends:
      file: docker-compose.base.yml
      service: powerberry-app
    build: ./powerberry-app
    volumes:
      - ./powerberry-app:/app

  powerberry-dsp:
    extends:
      file: docker-compose.base.yml
      service: powerberry-dsp
    build:
      context: ./powerberry-dsp
      target: dev
      args:
        IGNORE_ERRORS: 1
    volumes:
      - ./powerberry-dsp:/app
    environment:
      EMULATE_HARDWARE: emu_hw_true

  powerberry-redis:
    extends:
      file: docker-compose.base.yml
      service: powerberry-redis

  powerberry-influx:
    container_name: powerberry-influxdb
    image: influxdb:1.8.10
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  powerberry-grafana:
    container_name: powerberry-grafana
    image: grafana/grafana:8.4.6
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
