x-description: "production environment, with built images from sources"
version: "2.4"
services:
  powerberry-app:
    extends:
      file: docker-compose.base.yml
      service: powerberry-app
    build: ./powerberry-app

  powerberry-dsp:
    extends:
      file: docker-compose.base.yml
      service: powerberry-dsp
    build: ./powerberry-dsp
    volumes:
      - /sys:/app/sys

  powerberry-redis:
    extends:
      file: docker-compose.base.yml
      service: powerberry-redis
