name: build-powerberry-app

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            steckdoose4711/powerberry-app
            ghcr.io/steckdoose4711/powerberry-app
          tags: |
            type=sha
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container
        id: build
        uses: docker/build-push-action@v2
        with:
          context: powerberry-app
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/steckdoose4711/powerberry-app:buildcache
          cache-to: type=registry,ref=ghcr.io/steckdoose4711/powerberry-app:buildcache,mode=max
          platforms: |
            linux/amd64
            linux/arm/v7
